version: 2
general:
  artifacts:

do_steps: &do_steps
 steps:
  - run: echo "$CROSS_COMPILE" > ~/_cross_compile
  - restore_cache:
      key: code-tree-shallow-{{ .Environment.CACHE_VERSION }}
  - run:
      name: checkout build tree
      command: |
        mkdir -p ~/.ssh/
        pacman -Syy;
        pacman -S openssh --noconfirm;
        pacman -S git make wget unzip zip pandoc --noconfirm
        pacman -S jdk11-openjdk --noconfirm
        #source /etc/profile.d/jre.sh
        export JAVA_HOME=/usr/lib/jvm/java-11-openjdk/
        ssh-keyscan -H github.com >> ~/.ssh/known_hosts
        git clone --depth=1 --branch=master $CIRCLE_REPOSITORY_URL ~/project
        git reset --hard $CIRCLE_SHA1
  - run:
      name: get sdk & ndk
      command: |
        export JAVA_HOME=/usr/lib/jvm/java-11-openjdk/
        #source /etc/profile.d/jre.sh
        cd ~/project
        chmod a+x /root/project/scripts/setup-android-sdk.sh
        ~/project/scripts/setup-android-sdk.sh
  - run:
      name: build lkl
      command: |
        export PATH=${PATH}:/root/lib/android-ndk-r25b/toolchains/llvm/prebuilt/linux-x86_64/bin
        export JAVA_HOME=/usr/lib/jvm/java-11-openjdk/
        #source /etc/profile.d/jre.sh
        cd ~/project
        cd ~/project/tools/lkl && make ${MKARG} CROSS_COMPILE="aarch64-linux-android30-"
        zip -r ~/lkl.zip ~/project/tools/lkl
  - store_artifacts:
      path: ~/lkl.zip
      destination: lkl.zip
jobs:
  android-aarch64:
   docker:
     - image: archlinux:latest
   environment:
     CROSS_COMPILE: "aarch64-linux-android30-"
   <<: *do_steps
workflows:
  version: 2
  build:
    jobs:
     - android-aarch64

